### ISSUE TITLE
perf

### ISSUE THREAD

**Issue by asze17** [Tom-the-Bomb/brainfuck-web#1]
https://github.com/Tom-the-Bomb/brainfuck-web/blob/ca99c66449e6d130aa4c32e226cd377762c7e2b2/Cargo.toml#L35

hey tom if you want it to be faster then such should be removed, yeah the wasm might be bigger but it might be worth it tom. Up to you tom.

**Comment by Tom-the-Bomb** [comment]
Your name is cryptex; thank you for the suggestion cryptex
